#!/usr/bin/env tsx
/**
 * Reads migrations 0003-0011 (table-DDL migrations), rewrites table/index references
 * from `public.` to `test_schema.`, and emits 0012_test_schema_replicate.sql.
 */
import { readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

const MIGRATIONS_DIR = join(process.cwd(), "supabase", "migrations");
const OUT = join(MIGRATIONS_DIR, "0012_test_schema_replicate.sql");

const RANGE = /^(00(0[3-9]|1[01]))_/; // 0003..0011

function rewrite(sql: string): string {
  return sql
    // 1. Replace schema prefix in all qualified references public. → test_schema.
    .replace(/\bpublic\./g, "test_schema.")
    // 2. Indexes don't carry schema in their NAME (Postgres derives from table) so we keep
    // index NAMES unique by appending _ts so they don't collide with public ones in pg_indexes
    .replace(/CREATE\s+(UNIQUE\s+)?INDEX\s+(IF\s+NOT\s+EXISTS\s+)?([a-z0-9_]+)/gi,
      (_m, uniq, ifn, name) => `CREATE ${uniq ?? ""}INDEX ${ifn ?? ""}${name}_ts`)
    // 3. CREATE TYPE that already has test_schema. prefix (from step 1 rewriting public.order_status)
    //    → needs double-schema dedup: test_schema.test_schema.X → test_schema.X
    .replace(/\btest_schema\.test_schema\./g, "test_schema.")
    // 4. CREATE TYPE without any schema prefix → add test_schema explicitly
    //    (handles types that were defined as bare names, not public.foo)
    .replace(/CREATE\s+TYPE\s+(?!test_schema\.)([a-z0-9_]+)\s+AS\s+ENUM/gi,
      (_m, typ) => `CREATE TYPE test_schema.${typ} AS ENUM`)
    // 5. Bare unqualified type references in column defs: order_status → test_schema.order_status
    //    Only match when not already schema-qualified (not preceded by a dot or "test_schema.")
    .replace(/(?<![\w.])order_status\b/g, "test_schema.order_status")
    // 6. The DO $$ block in 0009 checks n.nspname = 'public' — needs to be 'test_schema'
    .replace(/n\.nspname\s*=\s*'public'/g, "n.nspname = 'test_schema'")
    // 7. The DO $$ block checks typname which is just the bare name (without schema)
    //    After step 1 rewrote 'order_status' references, the typname string literal
    //    should still match the bare type name in pg_type.typname.
    //    Fix: WHERE t.typname = 'test_schema.order_status' → t.typname = 'order_status'
    //    (pg_type.typname stores only the bare name; nspname identifies the schema)
    .replace(/t\.typname\s*=\s*'test_schema\.([a-z0-9_]+)'/g,
      (_m, name) => `t.typname = '${name}'`);
}

function main() {
  const files = readdirSync(MIGRATIONS_DIR).filter((f) => RANGE.test(f)).sort();
  if (files.length === 0) {
    console.error("No source migrations 0003-0011 found.");
    process.exit(1);
  }
  const header = `-- AUTO-GENERATED by scripts/generate-test-schema-migration.ts
-- Replicates migrations ${files[0]}..${files.at(-1)} inside test_schema.
-- DO NOT EDIT BY HAND. Regenerate with: pnpm tsx scripts/generate-test-schema-migration.ts
`;
  const body = files
    .map((f) => `-- === ${f} ===\n` + rewrite(readFileSync(join(MIGRATIONS_DIR, f), "utf8")))
    .join("\n\n");
  writeFileSync(OUT, header + "\n" + body + "\n");
  console.log(`[generate] wrote ${OUT} from ${files.length} sources.`);
}

main();
