-- AUTO-GENERATED by scripts/generate-test-schema-migration.ts
-- Replicates migrations 0003_core_users_anon_recipients.sql..0011_indexes_and_views.sql inside test_schema.
-- DO NOT EDIT BY HAND. Regenerate with: pnpm tsx scripts/generate-test-schema-migration.ts

-- === 0003_core_users_anon_recipients.sql ===
CREATE TABLE IF NOT EXISTS test_schema.users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth0_sub     text UNIQUE,
  email         text UNIQUE NOT NULL,
  name          text,
  balance_cents integer NOT NULL DEFAULT 0 CHECK (balance_cents >= 0),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS test_schema.anonymous_sessions (
  anonymous_id   uuid PRIMARY KEY,
  user_id        uuid REFERENCES test_schema.users(id) ON DELETE SET NULL,
  first_seen_at  timestamptz NOT NULL DEFAULT now(),
  last_seen_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS anonymous_sessions_user_idx_ts
  ON test_schema.anonymous_sessions(user_id) WHERE user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS test_schema.recipients (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES test_schema.users(id) ON DELETE CASCADE,
  name            text NOT NULL,
  gender          text CHECK (gender IN ('femenino', 'masculino', 'no_especifica')),
  age             smallint CHECK (age IS NULL OR (age >= 0 AND age <= 130)),
  address_cuba    jsonb,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recipients_user_idx_ts ON test_schema.recipients(user_id);


-- === 0004_products.sql ===
CREATE TABLE IF NOT EXISTS test_schema.products (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source              text NOT NULL,
  source_product_id   text NOT NULL,
  title               text NOT NULL,
  description         text NOT NULL DEFAULT '',
  price_cents         integer NOT NULL CHECK (price_cents >= 0),
  currency            text NOT NULL DEFAULT 'USD',
  image_url           text,
  raw_category        text,
  metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding           vector(1024),
  tsvector_es         tsvector GENERATED ALWAYS AS (
                        to_tsvector(
                          'spanish',
                          coalesce(title, '') || ' ' || coalesce(description, '')
                        )
                      ) STORED,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  last_refreshed_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT products_source_unique UNIQUE (source, source_product_id)
);

CREATE INDEX IF NOT EXISTS products_tsvector_idx_ts
  ON test_schema.products USING GIN (tsvector_es);

CREATE INDEX IF NOT EXISTS products_embedding_hnsw_idx_ts
  ON test_schema.products USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS products_metadata_gin_idx_ts
  ON test_schema.products USING GIN (metadata);

CREATE INDEX IF NOT EXISTS products_active_idx_ts
  ON test_schema.products (is_active) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS products_last_refreshed_idx_ts
  ON test_schema.products (last_refreshed_at);


-- === 0005_events.sql ===
CREATE TABLE IF NOT EXISTS test_schema.events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_event_id text,
  anonymous_id    uuid NOT NULL,
  user_id         uuid REFERENCES test_schema.users(id) ON DELETE SET NULL,
  session_id      uuid NOT NULL,
  event_type      text NOT NULL,
  occurred_at     timestamptz NOT NULL,
  payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
  source          text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS events_client_event_id_uniq_ts
  ON test_schema.events (client_event_id) WHERE client_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS events_anon_time_idx_ts
  ON test_schema.events (anonymous_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS events_user_time_idx_ts
  ON test_schema.events (user_id, occurred_at DESC) WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS events_type_time_idx_ts
  ON test_schema.events (event_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS events_session_idx_ts
  ON test_schema.events (session_id, occurred_at);


-- === 0006_personalization.sql ===
CREATE TABLE IF NOT EXISTS test_schema.user_profiles (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  anonymous_id            uuid,
  user_id                 uuid REFERENCES test_schema.users(id) ON DELETE CASCADE,
  n_events                integer NOT NULL DEFAULT 0,
  cohort_id               text,
  prior_vector            vector(1024),
  interpretable_profile   jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_recompute_at       timestamptz,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_identity_xor CHECK (
    (anonymous_id IS NOT NULL) OR (user_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_anon_uniq_ts
  ON test_schema.user_profiles (anonymous_id) WHERE anonymous_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_user_uniq_ts
  ON test_schema.user_profiles (user_id) WHERE user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS test_schema.user_profile_modes (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_profile_id       uuid NOT NULL REFERENCES test_schema.user_profiles(id) ON DELETE CASCADE,
  recipient_id          uuid REFERENCES test_schema.recipients(id) ON DELETE CASCADE,
  mode_index            smallint NOT NULL CHECK (mode_index BETWEEN 1 AND 3),
  vector_unnormalized   vector(1024) NOT NULL,
  weight_sum            double precision NOT NULL DEFAULT 0,
  n_events_in_mode      integer NOT NULL DEFAULT 0,
  last_assigned_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_profile_modes_uniq UNIQUE (user_profile_id, recipient_id, mode_index)
);

CREATE INDEX IF NOT EXISTS user_profile_modes_profile_idx_ts
  ON test_schema.user_profile_modes (user_profile_id);

CREATE TABLE IF NOT EXISTS test_schema.session_vectors (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id            uuid NOT NULL UNIQUE,
  vector_unnormalized   vector(1024) NOT NULL,
  weight_sum            double precision NOT NULL DEFAULT 0,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS test_schema.cohort_centroids (
  cohort_id           text PRIMARY KEY,
  centroid_vector     vector(1024) NOT NULL,
  n_users_in_cohort   integer NOT NULL DEFAULT 0,
  last_recompute_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS test_schema.excluded_products (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  anonymous_id    uuid,
  user_id         uuid REFERENCES test_schema.users(id) ON DELETE CASCADE,
  product_id      uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  excluded_at     timestamptz NOT NULL DEFAULT now(),
  ttl_until       timestamptz NOT NULL,
  CONSTRAINT excluded_products_identity_xor CHECK (
    (anonymous_id IS NOT NULL) OR (user_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS excluded_products_anon_ttl_idx_ts
  ON test_schema.excluded_products (anonymous_id, ttl_until) WHERE anonymous_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS excluded_products_user_ttl_idx_ts
  ON test_schema.excluded_products (user_id, ttl_until) WHERE user_id IS NOT NULL;


-- === 0007_co_occurrence.sql ===
CREATE TABLE IF NOT EXISTS test_schema.co_occurrence (
  product_a_id    uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  product_b_id    uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  count           double precision NOT NULL DEFAULT 0,
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (product_a_id, product_b_id),
  CONSTRAINT co_occurrence_ordered CHECK (product_a_id < product_b_id)
);

CREATE INDEX IF NOT EXISTS co_occurrence_b_a_idx_ts
  ON test_schema.co_occurrence (product_b_id, product_a_id);

CREATE TABLE IF NOT EXISTS test_schema.co_occurrence_top (
  product_id           uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  related_product_id   uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  npmi_score           double precision NOT NULL,
  rank                 smallint NOT NULL CHECK (rank BETWEEN 1 AND 50),
  last_recompute_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, related_product_id)
);

CREATE INDEX IF NOT EXISTS co_occurrence_top_rank_idx_ts
  ON test_schema.co_occurrence_top (product_id, rank);


-- === 0008_search.sql ===
CREATE TABLE IF NOT EXISTS test_schema.searches (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  anonymous_id       uuid,
  user_id            uuid REFERENCES test_schema.users(id) ON DELETE SET NULL,
  raw_query          text NOT NULL,
  normalized_json    jsonb,
  prompt_version     text,
  search_method      text CHECK (search_method IN ('like', 'bm25_only', 'cosine_only', 'hybrid_rrf')),
  results_count      integer,
  hit_cache          boolean,
  called_mock        boolean,
  occurred_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS searches_user_time_idx_ts
  ON test_schema.searches (user_id, occurred_at DESC) WHERE user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS test_schema.product_query_cache (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  query_hash          text NOT NULL UNIQUE,
  query_embedding     vector(1024),
  normalized_json     jsonb,
  products_returned   uuid[] NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  ttl_until           timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS product_query_cache_ttl_idx_ts
  ON test_schema.product_query_cache (ttl_until);

CREATE INDEX IF NOT EXISTS product_query_cache_embedding_idx_ts
  ON test_schema.product_query_cache USING hnsw (query_embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS test_schema.mock_calls (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  called_at       timestamptz NOT NULL DEFAULT now(),
  params          jsonb,
  response_size   integer,
  simulated_cost_cents integer NOT NULL DEFAULT 4,
  latency_ms      integer,
  was_error       boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS mock_calls_time_idx_ts ON test_schema.mock_calls (called_at DESC);


-- === 0009_orders.sql ===
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid
    WHERE t.typname = 'order_status' AND n.nspname = 'test_schema'
  ) THEN
    CREATE TYPE test_schema.order_status AS ENUM (
      'pendiente', 'comprada', 'en_bodega', 'en_transito',
      'para_entrega', 'entregada',
      'stock_fantasma', 'precio_subido', 'danada_o_no_entregada'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS test_schema.orders (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             uuid NOT NULL REFERENCES test_schema.users(id) ON DELETE RESTRICT,
  recipient_id        uuid REFERENCES test_schema.recipients(id) ON DELETE SET NULL,
  status              test_schema.order_status NOT NULL DEFAULT 'pendiente',
  total_charged_cents integer NOT NULL,
  total_cost_cents    integer NOT NULL,
  margin_cents        integer GENERATED ALWAYS AS (total_charged_cents - total_cost_cents) STORED,
  status_history      jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS orders_user_idx_ts ON test_schema.orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS orders_status_idx_ts ON test_schema.orders (status);

CREATE TABLE IF NOT EXISTS test_schema.order_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id            uuid NOT NULL REFERENCES test_schema.orders(id) ON DELETE CASCADE,
  product_id          uuid REFERENCES test_schema.products(id) ON DELETE SET NULL,
  product_snapshot    jsonb NOT NULL,
  quantity            integer NOT NULL CHECK (quantity > 0),
  unit_price_cents    integer NOT NULL CHECK (unit_price_cents >= 0),
  unit_cost_cents     integer NOT NULL CHECK (unit_cost_cents >= 0)
);

CREATE INDEX IF NOT EXISTS order_items_order_idx_ts ON test_schema.order_items (order_id);


-- === 0010_eval.sql ===
CREATE TABLE IF NOT EXISTS test_schema.eval_holdout (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES test_schema.users(id) ON DELETE CASCADE,
  product_id      uuid NOT NULL REFERENCES test_schema.products(id) ON DELETE CASCADE,
  purchased_at    timestamptz NOT NULL,
  used_in_eval    boolean NOT NULL DEFAULT false,
  CONSTRAINT eval_holdout_unique UNIQUE (user_id, product_id, purchased_at)
);

CREATE INDEX IF NOT EXISTS eval_holdout_unused_idx_ts
  ON test_schema.eval_holdout (used_in_eval) WHERE used_in_eval = false;


-- === 0011_indexes_and_views.sql ===
-- Reserved for Phase 0 closure checks; advanced indexes/views land in later phases.
-- Currently a no-op so the migration order has a stable slot for Phase 1+ additions.
SELECT 1;

